import { JSONSchemaType } from "ajv";
import { DataJSON, HealthJSON } from "./types";

export const HealthJSONSchema: JSONSchemaType<HealthJSON> = {
  type: "object",
  properties: {
    _id: {
      type: "string",
    },
    processed_data: {
      type: "object",
      properties: {
        start_time: {
          type: "number",
        },
        c1: {
          type: "object",
          properties: {
            arm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_operating_voltage: {
              $ref: "#/definitions/ProcessedHealthJSONType",
            },
          },
          required: ["arm_temp", "sipm_temp", "sipm_operating_voltage"],
        },
        m1: {
          type: "object",
          properties: {
            arm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_operating_voltage: {
              $ref: "#/definitions/ProcessedHealthJSONType",
            },
          },
          required: ["arm_temp", "sipm_temp", "sipm_operating_voltage"],
        },
        m5: {
          type: "object",
          properties: {
            arm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_operating_voltage: {
              $ref: "#/definitions/ProcessedHealthJSONType",
            },
          },
          required: ["arm_temp", "sipm_temp", "sipm_operating_voltage"],
        },
        x1: {
          type: "object",
          properties: {
            arm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            sipm_operating_voltage: {
              $ref: "#/definitions/ProcessedHealthJSONType",
            },
          },
          required: ["arm_temp", "sipm_temp", "sipm_operating_voltage"],
        },
        x123: {
          type: "object",
          properties: {
            board_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
            det_high_voltage: { $ref: "#/definitions/ProcessedHealthJSONType" },
            det_temp: { $ref: "#/definitions/ProcessedHealthJSONType" },
          },
          required: ["board_temp", "det_high_voltage", "det_temp"],
        },
      },
      required: ["start_time", "c1", "m1", "m5", "x1", "x123"],
    },
    raw_data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: {
            type: "string",
          },
          field: {
            type: "string",
          },
          unit: {
            type: "string",
          },
          data_type: {
            type: "string",
          },
          value: {
            type: "array",
            items: {
              type: "number",
            },
          },
        },
        required: ["type", "field", "unit", "value", "data_type"],
      },
    },
  },
  required: ["processed_data", "raw_data"],
  definitions: {
    ProcessedHealthJSONType: {
      type: "object",
      properties: {
        avg: {
          type: "number",
        },
        min: {
          type: "number",
        },
        max: {
          type: "number",
        },
      },
      required: ["avg", "min", "max"],
    },
  },
};

export const DataJSONSchema: JSONSchemaType<DataJSON> = {
  type: "object",
  properties: {
    _id: {
      type: "string",
      description: "UID generated by MongoDB",
    },
    processed_data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: {
            type: "string",
            description: "Detector or general information such as health",
          },
          group: {
            type: "string",
            description: "Group name such as SIPM Operating Voltage",
          },
          field: {
            type: "string",
            description: "Field name such as avg, min, or max",
          },
          unit: {
            type: "string",
            description: "Unit such as Voltage",
          },
          value: {
            type: "number",
            description: "Value",
          },
          data_type: {
            type: "string",
            description: "Is this a 1D, 2D, 3D ...",
          },
        },
        required: ["type", "group", "field", "unit", "value", "data_type"],
      },
      description: "Used for columns or quick find",
    },
    raw_data: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: {
            type: "string",
            description: "Detector or general information such as health",
          },
          field: {
            type: "string",
            description: "Field name such as SIPM Operating Voltage",
          },
          unit: {
            type: "string",
            description: "Unit such as Voltage",
          },
          value: {
            oneOf: [
              { type: "array", items: { type: "number" } }, // Allows array of any type
              {
                type: "array",
                items: { type: "array", items: { type: "number" } },
              },
            ],
            description: "Array of values",
          },
          data_type: {
            type: "string",
            description: "Is this a 1D, 2D, 3D ...",
          },
        },
        required: ["type", "field", "unit", "value", "data_type"],
      },
      description: "Used for graphing",
    },
  },
  required: ["processed_data", "raw_data"],
};
